### PR TITLE
Search Redesign

### PR DESCRIPTION
**Pull request by lmommaerts**

### CODE REVIEW

**Comment by lmommaerts** [comment]
Oops, found an issue. Fixing then I'll reassign

**Review by redreceipt — APPROVED** [review]
🎉

**Comment by redreceipt** [comment]
deployment is failing for some reason

**Comment by lmommaerts** [comment]
@redreceipt Looks like it might be something failing on the API?

Screen Shot 2021-05-13 at 2 27 03 PM

Could it be this line? https://github.com/Differential/longhollow-apollos/commit/e1c4dfeb36db0717158b79cd4c13f31714f39eba#diff-c27971b03627ab2f2fe5a7dceeea7b63547067e231da45170359cbc678cbad81R186

**Comment by redreceipt** [comment]
🤦‍♂️ fixed

**Comment by lmommaerts** [comment]
Not sure why it's still failing. Seems to be random watch pages that are loading fine locally. Will try just merging.

**Pull request merged**
